apiVersion : apps/v1
kind: Deployment
metadata:
  name: "azureaksmyappcluster-a1b2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "azureaksmyappcluster-a1b2"
  template:
    metadata:
      labels:
        app: "azureaksmyappcluster-a1b2"
    spec:
      containers:
        - name: "azureaksmyappcluster-a1b2"
          image: "aksmyappregistry.azurecr.io/azureaksmyappcluster"
          ports:
          - containerPort: 80