#Your build pipeline references an undefined variable named ‘Parameters.connectedServiceName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.WebAppName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: TestApp3026'
  inputs:
    azureSubscription: '$(Parameters.connectedServiceName)'
    appType: webApp
    appName: '$(Parameters.WebAppName)'
    package: '$(build.artifactstagingdirectory)/**/*.zip'
